### ISSUE TITLE
Adicionar uma licença

### ISSUE THREAD

**Issue by afonsopacifer** [all-animation/all-animation#11]
Acho importante escolher e adicionar uma licença para o projeto.
Da uma olhada nesse link que ajuda bastante na hora da escolha :)
http://escolhaumalicenca.com.br/

**Comment by clovisdasilvaneto** [comment]
Opa, boa! Já comecei a dar uma olhada ;)

**Comment by clovisdasilvaneto** [comment]
Licença criada ;)
