### ISSUE TITLE
gh-pages com conteúdo duplicado

### ISSUE THREAD

**Issue by afonsopacifer** [all-animation/all-animation#14]
Faaala @clovisdasilvaneto,
Então, existem muitos arquivos relacionados a documentação e outras coisas na gh-pages,
grande parte desse conteúdo já está na branch master. O problema é que fica dificil manter tudo atualizado, já que na master já tem dois idiomas para manter. A minha sugestão é deixar a gh-pages como um ambiente de produção mesmo, deixando só os arquivos do site, as demais documentações ficam na master que é a default.

Para não ter que ficar dando "deploy" na mão para a gh-pages toda hora, eu sugiro criar uma task no gulp para fazer isso, é assim que eu tenho usado nos meus projetos e tem ficado de boas :)

Se vc achar legal, eu posso mandar um PR com essas alterações ;)

Aproveitando: Feliz Ano Novo!

**Comment by clovisdasilvaneto** [comment]
@afonsopacifer que sugestão bacana cara, pode mandar o pr que eu faço o merge ;)
