### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by GuiAlmeida** [all-animation/all-animation#18]
Consigo adicionar as animacoes quando vou dando rolagem na pag?

**Comment by afonsopacifer** [comment]
Opa,
Consegue sim, basta utilizar o evento scroll do Jquery para adicionar a classe da animação onde você quiser.

Segue a documentação:
https://api.jquery.com/scroll/

Se precisar de alguma ajuda para implementar é só falar :)

cc @clovisdasilvaneto

**Comment by clovisdasilvaneto** [comment]
boa afonso, so pra complementar, caso o @GuiAlmeida queira fazer isto sem depender do jQuery, é só ultilizar o evento onscroll: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onscroll

**Comment by GuiAlmeida** [comment]
Obrigado galera!!!

**Comment by afonsopacifer** [comment]
@clovisdasilvaneto mandou bem :)
