### ISSUE TITLE
New structure - proposal

### ISSUE THREAD

**Issue by afonsopacifer** [all-animation/all-animation#19]
# Proposal

Initially , to facilitate the organization of the project , I think a good idea to create an organization for divide the repositories.
#### all-animation/all-animation

> The **core** project.

All animations and original css file (and min file) with all the original classes.
#### all-animation/all-animation.github.io

> The website, containing all the documentation.

we have the benefit of **changing the URL**:
clovisdasilvaneto.github.io/all-animation
to
all-animation.github.io
#### all-animation/all-animation-sass

> Semantic version

The idea is not depend to the classes for add animations , we will use mixins or placeholders to add animations(maintain semantic HTML and clean)
#### all-animation/all-animation-stylus

> Semantic version

The idea is not depend to the classes for add animations , we will use mixins or placeholders to add animations(maintain semantic HTML and clean)

**Note:** This is the first step to scale the project , we still have to define things related documentation and languages ​​that will be used

**Comment by clovisdasilvaneto** [comment]
very good @afonsopacifer 
Your proposal is very considerable.
thanks

**Comment by clovisdasilvaneto** [comment]
This issue will be solved when the issue https://github.com/all-animation/all-animation/issues/26 is fixed

**Comment by clovisdasilvaneto** [comment]
All animation now will have scss support by default and we got rid of stylus on **v3.0**, soon the relese of the new website will come.
