### ISSUE TITLE
Parse All Animation website from Electric

### ISSUE THREAD

**Issue by clovisdasilvaneto** [all-animation/all-animation#24]
Because good documentation is a must, and your project deserves better than a readme file.

Electric is a Node.js static generator that accelerates the process of writing detailed documentation sites.

**Comment by Nrsingj** [comment]
Sorry for friends

**Comment by Nrsingj** [comment]
Sorry

**Comment by clovisdasilvaneto** [comment]
New website will be done in gatsby
