### ISSUE TITLE
Navbar on documentation not working properly

### ISSUE THREAD

**Issue by Phe0** [all-animation/all-animation#30]
# :bug: Bug Report

When navbar itens are clicked the page does not scroll

# To Reproduce
![allanimation](https://user-images.githubusercontent.com/31973465/49678259-4cfe1f00-fa6a-11e8-8db2-d55456b60c79.gif)

When any of the options in the navbar are clicked the page stills the same 

# Expected Behavior
![smoothscroll](https://user-images.githubusercontent.com/31973465/49678269-6010ef00-fa6a-11e8-93f6-43ce27e93de9.gif)

When any of the options are clicked the page should have a smooth scroll animation to the right position

@RochaCarla

**Comment by clovisdasilvaneto** [comment]
Hi @Phe0 , thanks for reporting that behavior, I'll fix it

**Comment by clovisdasilvaneto** [comment]
Fixed on the new release of #37
