### ISSUE TITLE
syntax error at line 4422 to 4435 --portrait blur 

### ISSUE THREAD

**Issue by sohamnandi77** [all-animation/all-animation#32]
https://github.com/all-animation/all-animation/blob/859b31b4151672c9db35f251343f1d78fd7523e4/assets/css/all-animation.css#L4422

**Comment by clovisdasilvaneto** [comment]
@sohamnandi007 Thanks I'll fix it 👍

**Comment by clovisdasilvaneto** [comment]
Fixed at #37
