### ISSUE TITLE
Legend Flip

### ISSUE THREAD

**Issue by iamleniac** [all-animation/all-animation#4]
Olá, galera, tudo bom?
Estou com um problema de Cross Browser no efeito legend flip.
Ele funciona normalmente no Chrome, mas não está funcionando no firefox. 
Quando ocorre o efeito de giro, o background não aparece. Somente no chrome aparece...
Agradeço desde já...

**Comment by clovisdasilvaneto** [comment]
Opa, corrigido! o problema é que esta animação é feita com a propriedade, perspective do css3, mas como o mozila não suporta, deu bug, obrigado pela Issue amigo :D
